In [5]:
import numpy as np
import pandas as pd

In [6]:
#  <------- SERIES IN PANDAS ------->

In [7]:
labels = ['a','b','c']
list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30,'a':40,'b':50,'c':60}

In [8]:
pd.Series(d)

1    10
2    20
3    30
a    40
b    50
c    60
dtype: int64

In [9]:
# <------- DATAFRAMES IN PANDAS ------->

In [10]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [11]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list, columns = columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [12]:
#SELECTION AND INDEXING OF COLUMNS

In [13]:
df2[['Name','City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [14]:
#CREATING A NEW COLUMN

In [15]:
df2['Designation'] = ['CEO','Manager','HR', 'Developer']
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000         CEO
1   Anna   34     Paris   70000     Manager
2  Peter   29    Berlin   62000          HR
3  Linda   42    London   85000   Developer

In [16]:
#REMOVING COLUMNS

In [17]:
df2.drop( 1, axis = 0)
#df2.drop( 0, axis = 0, inplace = True)
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000         CEO
1   Anna   34     Paris   70000     Manager
2  Peter   29    Berlin   62000          HR
3  Linda   42    London   85000   Developer

In [18]:
#SELECTING ROWS

In [19]:
df2.loc[[0,1]]

   Name  Age      City  Salary Designation
0  John   28  New York   65000         CEO
1  Anna   34     Paris   70000     Manager

In [20]:
df2.iloc[[1]]

   Name  Age   City  Salary Designation
1  Anna   34  Paris   70000     Manager

In [21]:
#SELECTING SUBSETS OF ROWS AND COLUMNS

In [22]:
df2.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [23]:
df2.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [24]:
#CONDITIONAL SELECTION

In [25]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000         CEO
1   Anna   34     Paris   70000     Manager
2  Peter   29    Berlin   62000          HR
3  Linda   42    London   85000   Developer

In [26]:
#I only want poeple whose age is above 30 and their city must be paris

In [27]:
df2[(df2['Age'] > 30) & (df2['City'] == 'Paris')]

   Name  Age   City  Salary Designation
1  Anna   34  Paris   70000     Manager

In [28]:
#<------- MISSING DATA ------->

In [29]:
#FINDING MISSING DATA

In [30]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [31]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [32]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [33]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [34]:
#REMOVING MISSING DATA

In [35]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [36]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [37]:
#FILLING THE MISSING DATA

In [38]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [39]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [40]:
values = {'A':100,'B':200,'C':300,'D':400}
df.fillna(value = values)

       A  B      C      D
0    1.0  1    1.0    1.0
1    2.0  2    2.0  400.0
2  100.0  3    3.0  400.0
3    4.0  4  300.0  400.0
4    5.0  5  300.0    5.0

In [41]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [42]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [43]:
#<------- MERGING JOINING AND CONCATINATION ------->

In [44]:
#MERGING 2 DATA FRAMES

In [45]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [46]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [47]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [48]:
pd.merge(employees,salaries,on= 'employee_id', how = 'inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [49]:
pd.merge(employees,salaries,on= 'employee_id', how = 'outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [50]:
pd.merge(employees,salaries,on= 'employee_id', how = 'left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [51]:
pd.merge(employees,salaries,on= 'employee_id', how = 'right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [52]:
#CONCATINATION OF 2 DATA FRAMES

In [53]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [54]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [55]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [56]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [57]:
pd.concat([df1,df2],axis = 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [58]:
#JOINING OF 2 DATA FRAMES

In [59]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [60]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [61]:
df2

   score
2     85
3     90
4     75

In [62]:
df1.join(df2, how = 'inner')

      name  score
2      Bob     85
3  Charlie     90

In [63]:
df1.join(df2, how = 'outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [64]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

In [65]:
#<------- GROUP BY AGGREGATION ------->

In [66]:
#GROUP BY

In [67]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [68]:
# Group by Category and calculate the sum of Sales
cat = df.groupby('Category')['Sales'].sum()
cat 
# for i,v in cat:
#     print(i)
#     print(v)

Category
A    570
B    930
Name: Sales, dtype: int64

In [69]:
# Group by Store and calculate the sum of Sales
str = df.groupby('Store')['Sales'].sum()
str

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [70]:
# Group by multiple columns
# Group by Category and Store
col = df.groupby(['Category','Store'])['Sales'].sum()
col

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [71]:
#AGGREGATION

In [72]:
df['Sales'].mean()

np.float64(187.5)

In [73]:
df['Sales'].agg(['sum', 'mean', 'min', 'max', 'count', 'std', 'median'])

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

In [74]:
#<------- PIVOT TABLES ------->

In [75]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype('string')
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    577     65   John  January      Q1
1  2023-01-02       B   West    992     27   Mary  January      Q1
2  2023-01-03       C  North    441     42    Bob  January      Q1
3  2023-01-04       D  South    901     57  Alice  January      Q1
4  2023-01-05       A   East    851     99   John  January      Q1
5  2023-01-06       B   West    640     82   Mary  January      Q1
6  2023-01-07       C  North    833     72    Bob  January      Q1
7  2023-01-08       D  South    856     42  Alice  January      Q1
8  2023-01-09       A   East    509     32   John  January      Q1
9  2023-01-10       B   West    167     12   Mary  January      Q1
10 2023-01-11       C  North    276     31    Bob  January      Q1
11 2023-01-12       D  South    390     54  Alice  January      Q1
12 2023-01-13       A   East    756     12   John  January      Q1
13 2023-01-14       B   West    619     64   Mary  January      Q1
14 2023-01-15       C  North    704     84    Bob  January      Q1
15 2023-01-16       D  South    726     56  Alice  January      Q1
16 2023-01-17       A   East    892     97   John  January      Q1
17 2023-01-18       B   West    458     83   Mary  January      Q1
18 2023-01-19       C  North    332     18    Bob  January      Q1
19 2023-01-20       D  South    761     42  Alice  January      Q1

In [76]:
pd.pivot_table(df, values = 'Sales', index = 'Region', columns = 'Product', aggfunc = 'median')

Product      A      B      C      D
Region
East     756.0    NaN    NaN    NaN
North      NaN    NaN  441.0    NaN
South      NaN    NaN    NaN  761.0
West       NaN  619.0    NaN    NaN

In [77]:
pivot2 = pd.pivot_table(df, values = ['Sales', 'Units'], index = 'Region', columns = 'Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     717.0    NaN    NaN    NaN  61.0   NaN   NaN   NaN
North      NaN    NaN  517.2    NaN   NaN   NaN  49.4   NaN
South      NaN    NaN    NaN  726.8   NaN   NaN   NaN  50.2
West       NaN  575.2    NaN    NaN   NaN  53.6   NaN   NaN

In [78]:
#CROSS TABS

In [79]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [80]:
#<------- OPERATIONS ------->

In [81]:
#DATAFRAMES BASIC OPERATIONS

In [82]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [83]:
df1.shape

(5, 3)

In [84]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [85]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [86]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [87]:
df1['B'] + 10

0    20
1    30
2    40
3    50
4    60
Name: B, dtype: int64

In [88]:
#DATAFRAMES APPLYING FUNCTIONS

In [89]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [90]:
def square(x):
    return x**2

df1["B"].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [91]:
df1['D'] = df1["B"].apply(lambda x : x**2)

In [92]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500